export class AbortError extends DOMException {
  static isAbortError(e: unknown) {
    return e instanceof DOMException && e.name === AbortError.Name
  }

  // name used for the DOMException generated by the browser when an AbortController is cancelled
  static Name = 'AbortError'

  constructor(source: string) {
    super(`source: ${source}`, AbortError.Name)
  }
}
