import {
  type Cancellable,
  type CancellablePromiseDisposer,
} from 'cancel/Cancellable'
import { isCancellationError } from 'cancel/isCancellationError'
import { type LooseCancellableIterable } from 'cancel/iteration/CancellableIterable'
import { isAsyncIterable } from 'cancel/iteration/isAsyncIterable'
import { isIterable } from 'cancel/iteration/isIterable'
/* oxlint-disable typescript/no-explicit-any, typescript/no-non-null-assertion -- generic promise/iterator plumbing */
import { fromPromise, type IPromiseBasedObservable } from 'mobx-utils'
import {
  CancellablePromise as CancellablePromiseImpl,
  Cancellation,
  isPromiseWithCancel,
  type PromiseWithCancel,
} from 'real-cancellable-promise'
import { type Maybe } from 'types/Maybe'
import {
  createDelay,
  type Delay,
  delayAnimationFrame,
  infiniteDelay,
} from 'util/delay'
import { isPromiseLike } from 'util/isPromiseLike'

export { Cancellation } from 'real-cancellable-promise'

export class CancellableIterableCompletedError<TReturn> extends Cancellation {
  constructor(readonly returnValue: TReturn) {
    super()
  }
}

export class ToValuesPromiseError<T> extends Error {
  constructor(
    cause: unknown,
    readonly values: T[],
  ) {
    super('error consuming async iterator', {
      cause,
    })
  }
}

export type CancellablePromiseBasedObservable<T> =
  IPromiseBasedObservable<T> & {
    cancel: () => void
  }

export type CancellablePromiseFromIterableOptions<T> = {
  wrapper?: (f: () => void) => void
  consumer?: (v: T) => CancellablePromise<void> | void
  blocking?: boolean
}

export class CancellablePromise<T> extends CancellablePromiseImpl<T> {
  /**
   * Converts the cancellable to a promise, unless it is a non-deferred value (not an iterator or a promise)
   */
  static maybeFromCancellable<T>(
    cancellable: Cancellable<T> | PromiseLike<T> | PromiseWithCancel<T>,
  ): CancellablePromise<T> | T {
    if (isIterable(cancellable)) {
      return CancellablePromise.fromIterable(cancellable)
    }
    if (isPromiseWithCancel(cancellable)) {
      if (cancellable instanceof CancellablePromiseImpl) {
        return cancellable
      }
      // assume it's a degenerate implementation of promise-with-cancel that will
      // lose the cancel-ability if then-ed
      return new CancellablePromise(cancellable, () => {
        cancellable.cancel()
      })
    }
    if (isPromiseLike(cancellable)) {
      return CancellablePromise.fromPromiseWithoutCancel(cancellable)
    }
    return cancellable
  }

  /**
   * Converts the cancellable to a promise
   */
  static fromCancellable<T>(
    cancellable: Cancellable<T> | PromiseLike<T> | PromiseWithCancel<T>,
  ): CancellablePromise<T> {
    const maybePromise = CancellablePromise.maybeFromCancellable(cancellable)
    if (isPromiseWithCancel(maybePromise)) {
      return maybePromise
    }
    return CancellablePromise.resolve(maybePromise)
  }

  static toObservable<T>(
    c: Cancellable<T>,
  ): CancellablePromiseBasedObservable<T> {
    const p = CancellablePromise.fromCancellable(c)
    const o = fromPromise(p) as CancellablePromiseBasedObservable<T>
    // mobx fromPromise throws away errors by default (you can observe them, but we still want the
    // trace) which is not what we ever want; the promise is already observed via `o`, so this only
    // swallows the trailing cancellation. The rethrow path is never actioned.
    void CancellablePromise.ignoreCancellationErrors(p)
    // avoid circular calls
    const originalCancel = p.cancel
    // ensure that there isn't already a cancel operation on the returned promise
    // oxlint-disable-next-line typescript/no-unnecessary-condition -- fromPromise may return an observable without a cancel, despite the type
    o.cancel ??= (reason?: string) => originalCancel?.call(o, reason)
    return o
  }

  /**
   * fakes the cancellation by racing the promise and cancelling the raced promise. The supplied promise will
   * complete normally but not block anything waiting the returned CancellablePromise. Only use this if you
   * have no other choice
   * @param promise the promise to fake cancel
   * @returns a cancellable promise
   */
  static fromPromiseWithoutCancel<V>(
    promise: PromiseLike<V>,
  ): CancellablePromise<V> {
    const infinite = CancellablePromise.infinite<V>()
    return new CancellablePromise(Promise.race([promise, infinite]), () =>
      infinite.cancel(),
    )
  }

  /**
   * Converts an iterator to a promise, returning all the values generated by an iterator along with the return type.
   * Will also package up any errors to contain the values as a ToValuesPromiseError.
   *
   * only exposed for testing, iterate the generator yourself if you want the values
   */
  static valuesFromIterable<T, TReturn>(
    g: AsyncIterable<T, TReturn> | LooseCancellableIterable<T, TReturn>,
  ): CancellablePromise<{ values: T[]; returnValue: TReturn }> {
    const values: T[] = []
    const options = {
      blocking: true,
      consumer: (v: T) => {
        values.push(v)
      },
    }
    const promise = isAsyncIterable(g)
      ? CancellablePromise.fromAsyncIterable(g, options)
      : CancellablePromise.fromIterable(g, options)

    return promise
      .then((returnValue) => ({ returnValue, values }))
      .catch((e) => {
        throw new ToValuesPromiseError(e, values)
      })
  }

  /**
   * Creates a CancellablePromise from an Generator/Iterator/Iterable
   * @param g the Iterable/Iterator you want to convert to a promise
   *
   * only exposed for testing, use fromCancellable instead
   */
  static fromIterable<
    G extends Iterable<unknown, any, CancellablePromiseDisposer>,
  >(
    g: G,
    {
      wrapper = (f: () => void) => f(),
      consumer,
      blocking,
    }: CancellablePromiseFromIterableOptions<
      G extends Iterable<infer T> ? Awaited<T> : never
    > = {},
  ): G extends Iterable<infer _T, infer TReturn>
    ? CancellablePromise<Awaited<TReturn>>
    : never {
    // Named after the parameters of the `Iterable<T, TReturn>` interface being consumed, so the
    // helpers below read in those terms. The conditional return type erases the concrete values to
    // `unknown` at the iterator-protocol boundary, so those crossings are bridged with casts.
    type T = G extends Iterable<infer U> ? Awaited<U> : never
    type TReturn = G extends Iterable<infer _U, infer R> ? Awaited<R> : never

    const i = (isIterable(g) ? g[Symbol.iterator]() : g) as Iterator<
      CancellablePromise<T> | T,
      TReturn,
      CancellablePromiseDisposer
    >
    let cancellation: Cancellation | undefined
    // the single promise the loop is currently awaiting (an `all` of the yielded value plus the
    // optional frame delay, or a consumer's promise). Cancelling reaches into it directly rather
    // than threading cancellation through a per-iteration promise chain, so nothing is retained
    // between iterations.
    let pending: CancellablePromise<unknown> | undefined
    const cancel = () => {
      cancellation ??= new Cancellation('iterator cancelled')
      pending?.cancel()
    }
    // awaits `p` while exposing it to `cancel`. If cancellation already arrived synchronously
    // (e.g. the iterator called its disposer inside `i.next`), cancel `p` before awaiting it.
    const track = <V>(p: CancellablePromise<V>): CancellablePromise<V> => {
      pending = p
      if (cancellation != null) {
        p.cancel()
      }
      return p
    }
    const step = (
      maybeError: Maybe<unknown>,
    ): IteratorResult<CancellablePromise<T> | T, TReturn> => {
      try {
        let result:
          | IteratorResult<CancellablePromise<T> | T, TReturn>
          | undefined
        wrapper(() => {
          result =
            maybeError == null
              ? // allow iterators to access a destructor when calling yield
                i.next(cancel)
              : i.throw!(maybeError[0])
        })
        // wrapper invokes its callback synchronously
        return result!
      } catch (e) {
        // make any synchronous errors into failing iterators (assume synchronous errors can only
        // come from iterators, not async iterators)
        return {
          done: false,
          value: CancellablePromise.reject(e),
        }
      }
    }
    const consume = async (value: T): Promise<void> => {
      if (consumer == null) {
        return
      }
      const consumed = consumer(value)
      if (consumed != null) {
        await track(CancellablePromise.fromCancellable(consumed))
      }
    }
    // decides what to do when awaiting a yielded value throws: hand the error back to the
    // generator to handle, finish with a return value, or rethrow. The caught error is untyped
    // (any value can be thrown); boxing it for re-throwing is the caller's concern.
    const handleCaught = (
      e: unknown,
      maybeError: Maybe<unknown>,
    ): { retry: unknown } | { finished: TReturn } => {
      if (
        i.throw == null ||
        // throwing the same error reference multiple times indicates that the generator
        // is not handling the error
        (maybeError != null && maybeError[0] === e)
      ) {
        if (e instanceof CancellableIterableCompletedError) {
          return { finished: e.returnValue as TReturn }
        }
        throw e
      }
      return { retry: e }
    }
    // awaits a single yielded value (alongside the frame delay that paces non-blocking loops) and
    // feeds any resolved value to the consumer. Returns the error to hand back to the generator on
    // the next step, or a terminal return value.
    const awaitStep = async (
      value: T | CancellablePromise<T>,
      maybeError: Maybe<unknown>,
    ): Promise<{ error: Maybe<unknown> } | { finished: TReturn }> => {
      try {
        const [resolved] = await track(
          CancellablePromise.all([
            CancellablePromise.fromCancellable(value),
            blocking ? null : delayAnimationFrame(),
          ]),
        )
        await consume(resolved)
        return { error: null }
      } catch (e) {
        const outcome = handleCaught(e, maybeError)
        return 'finished' in outcome ? outcome : { error: [outcome.retry] }
      }
    }
    const run = async (): Promise<TReturn> => {
      let maybeError: Maybe<unknown> = null
      for (;;) {
        if (cancellation != null && maybeError == null) {
          maybeError = [cancellation]
        }
        const result = step(maybeError)
        if (result.done) {
          return result.value
        }
        const outcome = await awaitStep(result.value, maybeError)
        if ('finished' in outcome) {
          return outcome.finished
        }
        maybeError = outcome.error
      }
    }

    return new CancellablePromise<TReturn>(run(), cancel) as any
  }

  /**
   * Turns an async iterator/iterable into a CancellablePromise. The cancellation is unreliable, so
   * best to avoid using this in production
   */
  static fromAsyncIterable<T, TReturn>(
    g: AsyncIterator<T, TReturn, void> | AsyncIterable<T, TReturn, void>,
    {
      consumer,
    }: Omit<
      CancellablePromiseFromIterableOptions<T>,
      'wrapper' | 'blocking'
    > = {},
  ): CancellablePromise<TReturn> {
    const i = isAsyncIterable(g) ? g[Symbol.asyncIterator]() : g
    let cancelled = false
    let currentPromise: Promise<IteratorResult<T, TReturn>> | undefined
    const next = async (): Promise<TReturn> => {
      currentPromise = i.next()
      const { value, done } = await currentPromise
      if (cancelled) {
        const error = new Cancellation('async iterable cancelled')
        if (i.throw == null) {
          throw error
        }
        // very unlikely this will do anything while awaiting a promise given how async iterators work
        await CancellablePromise.ignoreCancellationErrors(i.throw())
      }
      if (done) {
        return value
      }
      await consumer?.(value)
      return next()
    }
    // hide cancellation errors to avoid test failures
    const promise = CancellablePromise.ignoreCancellationErrors(
      next(),
      // cast it back, as we are racing the promise and it can only return void when it fails with
      // a cancellation error, and the infinite promise will always throw an error anyway, we cannot
      // actually return nothing
    ) as Promise<TReturn>
    const infinite = CancellablePromise.infinite<Awaited<TReturn>>()
    return new CancellablePromise(
      CancellablePromise.race([promise, infinite]),
      () => {
        if (isPromiseWithCancel(currentPromise)) {
          // very unlikely the current promise will expose a cancel operation given how async iterators work
          currentPromise.cancel()
        }
        // fake exit immediately
        infinite.cancel()
        cancelled = true
      },
    )
  }

  /**
   * Creates a CancellablePromise that never returns (unless it is cancelled)
   */
  static infinite<T = void>(): CancellablePromise<T> {
    return infiniteDelay<T>()
  }

  /**
   * Makes it so the promise will ignore cancellation errors. Some promises are very noisy otherwise
   */
  static ignoreCancellationErrors<
    P extends CancellablePromise<unknown> | Promise<unknown>,
  >(
    p: P,
  ): P extends CancellablePromise<infer TReturn>
    ? CancellablePromise<TReturn | undefined>
    : P extends Promise<infer TReturn>
      ? Promise<TReturn | undefined>
      : never {
    return p.catch((e) => {
      if (!isCancellationError(e)) {
        throw e
      }
    }) as any
  }

  /**
   * Turns a synchronous method into a cancellable, asynchronous method with a delay
   */
  static fromPseudoAsync<A extends any[], TReturn>(
    f: (...args: A) => Promise<TReturn> | TReturn,
    delay: Delay = createDelay(0),
  ): (...args: A) => CancellablePromise<TReturn> {
    return (...args: A) => delay().then(() => Promise.resolve(f(...args)))
  }

  /**
   * Implementation of race that immediately cancels the promises that lose the race
   * @param promises the promises to race
   */
  static raceAndCancelLosers<T>(
    cancellables: readonly Cancellable<T>[],
    canCancel: (cancellable: Cancellable<T>, index: number) => boolean = () =>
      true,
  ): CancellablePromise<Awaited<T>> {
    const promises = cancellables.map(CancellablePromise.fromCancellable)
    const maybeQuitOthers = (exceptIndex: number) => {
      // need to defer otherwise we trigger a bunch of cascading errors from all the canceled
      // promises throwing errors and cancelling the winner
      if (winner == null) {
        winner = exceptIndex
        indexedPromises.forEach((promise, index) => {
          if (canCancel(promises[index], index) && index !== exceptIndex) {
            promise.cancel()
          }
        })
      }
    }
    let winner: number | undefined
    let result: T
    const indexedPromises = promises.map((promise, index) =>
      promise
        .then((v) => {
          maybeQuitOthers(index)
          result = v
          return v
        })
        .catch((e) => {
          const isWinner = winner == null
          maybeQuitOthers(index)
          // if there is no winner yet, allow cancellation errors
          if (!isCancellationError(e) || isWinner) {
            throw e
          }
          // fall back to returning the success result if we somehow get here
          return result
        }),
    )
    // there will always be a result or an error even if the individual promises may not return a value
    return CancellablePromise.race(indexedPromises)
  }
}
