# act workflow_dispatch --workflows ".\.github\workflows\workflow_call_validate.yaml"

name: CI

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Run install
        run: pnpm install --frozen-lockfile
      - name: Check if lockfile was modified
        run: |
          if [[ `git status --porcelain pnpm-lock.yaml` ]]; then
            echo "The pnpm-lock.yaml file has been modified. Please commit the updated lockfile."
            exit 1
          fi
      - name: Run typechecking
        run: pnpm check-types
      - name: Run linting
        run: pnpm lint
      - name: Run tests
        run: pnpm test
      - name: Run storybook tests
        run: pnpm storybook:test
      - name: Run build
        run: pnpm build
